# translate.py
import json
import re

translations = {
    'en': {
        'selectYourPlan': 'Select your Plan',
        'unlockFullClarity': 'Unlock Full Market Clarity',
        'selectPlatformPackage': 'Select Platform Package',
        'planMonthly': 'Monthly Plan',
        'planQuarterly': 'Quarterly Plan',
        'planSemiAnnual': 'Semi-Annual Plan',
        'planAnnual': 'Annual Plan',
        'billedEvery3Months': 'Billed Every 3 Months',
        'billedEvery6Months': 'Billed Every 6 Months',
        'billedEveryYear': 'Billed Every Year',
        'save10': 'Save 10%',
        'save15': 'Save 15%',
        'save20': 'Save 20%',
        'aiMarketAddon': 'AI Market Add-on',
        'phaseXCoreRadar': 'Phase X Core AI Radar',
        'aiAddonDesc': 'Gain live conversational context and advanced execution signals with the Phase-X Neural Network.',
        'perMonthSub': '+$20/month',
        'aiTokensIncluded': '3,000 AI Tokens',
        'tokensRollOver': 'Tokens roll over while subscription is active.',
        'paymentProcessing': 'Payment Processing',
        'paymentDesc': 'We currently accept USDT TRC-20 and Telegram verification for early access members.',
        'networkUsdt': 'USDT TRC-20 Network',
        'copyAddress': 'Copy Address',
        'addressCopied': 'Copied!',
        'telegramSupport': 'Telegram Support',
        'telegramSupportDesc': 'Contact our support agents via Telegram to bypass the queue.',
        'uploadReceipt': 'Upload Payment Receipt',
        'submitReceipt': 'Submit Receipt',
        'processingReceipt': 'Processing...',
        'verificationPending': 'Verification Pending',
        'verificationDesc': 'Your receipt is being reviewed by our compliance team. Access will be granted within 2-4 hours.',
        'accountDashboard': 'Account Dashboard',
        'terminalAccess': 'Phase-X Terminal Access',
        'managePlan': 'Manage Plan',
        'aiAnalytics': 'AI Analytics',
        'tokensLabel': 'Tokens',
        'liveProcessingActive': 'Live Processing Active',
        'integrationInactive': 'Integration Inactive',
        'topUpTokens': 'Top-up Tokens',
        'unlockAiAddon': 'Unlock AI Add-on',
        'billingCycle': 'Billing Cycle',
        'nextPaymentDue': 'Next payment due in 14 days.',
        'aiMarketInsight': 'AI MARKET INSIGHT',
        'userProfile': 'User Profile'
    },
    'ar': {
        'selectYourPlan': 'اختر باقتك',
        'unlockFullClarity': 'افتح الرؤية الكاملة للسوق',
        'selectPlatformPackage': 'اختر باقة المنصة',
        'planMonthly': 'الباقة الشهرية',
        'planQuarterly': 'الباقة الربع سنوية',
        'planSemiAnnual': 'الباقة النصف سنوية',
        'planAnnual': 'الباقة السنوية',
        'billedEvery3Months': 'فاتورة كل 3 أشهر',
        'billedEvery6Months': 'فاتورة كل 6 أشهر',
        'billedEveryYear': 'فاتورة كل عام',
        'save10': 'وفر 10%',
        'save15': 'وفر 15%',
        'save20': 'وفر 20%',
        'aiMarketAddon': 'إضافة سوق الذكاء الاصطناعي',
        'phaseXCoreRadar': 'رادار الذكاء الاصطناعي Phase X Core',
        'aiAddonDesc': 'احصل على سياق محادثة مباشر وإشارات تنفيذ متقدمة مع الشبكة العصبية لـ Phase-X.',
        'perMonthSub': '+$20/شهر',
        'aiTokensIncluded': '3,000 توكن AI',
        'tokensRollOver': 'تنتقل التوكنز معك طالما أن الاشتراك نشط.',
        'paymentProcessing': 'معالجة الدفع',
        'paymentDesc': 'نقبل حالياً USDT TRC-20 وتفعيل التليجرام لأعضاء الوصول المبكر.',
        'networkUsdt': 'شبكة USDT TRC-20',
        'copyAddress': 'نسخ العنوان',
        'addressCopied': 'تم النسخ!',
        'telegramSupport': 'دعم التليجرام',
        'telegramSupportDesc': 'تواصل مع وكلاء الدعم لدينا عبر التليجرام لتخطي طابور الانتظار.',
        'uploadReceipt': 'رفع إيصال الدفع',
        'submitReceipt': 'إرسال الإيصال',
        'processingReceipt': 'جاري المعالجة...',
        'verificationPending': 'في انتظار المراجعة',
        'verificationDesc': 'يتم مراجعة إيصالك من قبل فريق الامتثال. سيتم منح الوصول خلال 2-4 ساعات.',
        'accountDashboard': 'لوحة تحكم الحساب',
        'terminalAccess': 'الوصول لمنصة Phase-X',
        'managePlan': 'إدارة الباقة',
        'aiAnalytics': 'تحليلات الذكاء الاصطناعي',
        'tokensLabel': 'توكنز',
        'liveProcessingActive': 'المعالجة المباشرة نشطة',
        'integrationInactive': 'التكامل غير نشط',
        'topUpTokens': 'شحن التوكنز',
        'unlockAiAddon': 'فتح إضافة الذكاء الاصطناعي',
        'billingCycle': 'دورة الفوترة',
        'nextPaymentDue': 'الدفعة التالية مستحقة خلال 14 يوم.',
        'aiMarketInsight': 'نظرة سوق الذكاء الاصطناعي',
        'userProfile': 'الملف الشخصي'
    },
    'fr': {
        'selectYourPlan': 'Sélectionnez votre Plan',
        'unlockFullClarity': 'Débloquez la Clarté du Marché',
        'selectPlatformPackage': 'Sélectionnez le Forfait Plateforme',
        'planMonthly': 'Forfait Mensuel',
        'planQuarterly': 'Forfait Trimestriel',
        'planSemiAnnual': 'Forfait Semestriel',
        'planAnnual': 'Forfait Annuel',
        'billedEvery3Months': 'Facturé Tous les 3 Mois',
        'billedEvery6Months': 'Facturé Tous les 6 Mois',
        'billedEveryYear': 'Facturé Chaque Année',
        'save10': 'Économisez 10%',
        'save15': 'Économisez 15%',
        'save20': 'Économisez 20%',
        'aiMarketAddon': 'Module IA de Marché',
        'phaseXCoreRadar': 'Radar IA Phase X Core',
        'aiAddonDesc': 'Obtenez un contexte conversationnel en direct et des signaux avec le réseau neuronal Phase-X.',
        'perMonthSub': '+20$/mois',
        'aiTokensIncluded': '3 000 Jetons IA',
        'tokensRollOver': 'Les jetons sont reportés tant que l\'abonnement est actif.',
        'paymentProcessing': 'Traitement du Paiement',
        'paymentDesc': 'Nous acceptons actuellement l\'USDT TRC-20 et Telegram pour les membres.',
        'networkUsdt': 'Réseau USDT TRC-20',
        'copyAddress': 'Copier l\'Adresse',
        'addressCopied': 'Copié!',
        'telegramSupport': 'Support Telegram',
        'telegramSupportDesc': 'Contactez nos agents via Telegram pour contourner la file d\'attente.',
        'uploadReceipt': 'Télécharger le Reçu',
        'submitReceipt': 'Soumettre le Reçu',
        'processingReceipt': 'Traitement...',
        'verificationPending': 'Vérification en Attente',
        'verificationDesc': 'Votre reçu est en cours de révision. L\'accès sera accordé dans 2-4 heures.',
        'accountDashboard': 'Tableau de Bord du Compte',
        'terminalAccess': 'Accès au Terminal Phase-X',
        'managePlan': 'Gérer le Forfait',
        'aiAnalytics': 'Analytiques IA',
        'tokensLabel': 'Jetons',
        'liveProcessingActive': 'Traitement en Direct Actif',
        'integrationInactive': 'Intégration Inactive',
        'topUpTokens': 'Recharger les Jetons',
        'unlockAiAddon': 'Débloquer le Module IA',
        'billingCycle': 'Cycle de Facturation',
        'nextPaymentDue': 'Prochain paiement dans 14 jours.',
        'aiMarketInsight': 'APERCU DU MARCHÉ IA',
        'userProfile': 'Profil Utilisateur'
    },
    'es': {
        'selectYourPlan': 'Selecciona tu Plan',
        'unlockFullClarity': 'Desbloquea la Claridad del Mercado',
        'selectPlatformPackage': 'Selecciona el Paquete de Plataforma',
        'planMonthly': 'Plan Mensual',
        'planQuarterly': 'Plan Trimestral',
        'planSemiAnnual': 'Plan Semestral',
        'planAnnual': 'Plan Anual',
        'billedEvery3Months': 'Facturado Cada 3 Meses',
        'billedEvery6Months': 'Facturado Cada 6 Meses',
        'billedEveryYear': 'Facturado Cada Año',
        'save10': 'Ahorra 10%',
        'save15': 'Ahorra 15%',
        'save20': 'Ahorra 20%',
        'aiMarketAddon': 'Complemento de IA',
        'phaseXCoreRadar': 'Radar IA Phase X Core',
        'aiAddonDesc': 'Obtén contexto en vivo y señales avanzadas con la Red Neuronal Phase-X.',
        'perMonthSub': '+$20/mes',
        'aiTokensIncluded': '3,000 Tokens de IA',
        'tokensRollOver': 'Los tokens se acumulan mientras la suscripción esté activa.',
        'paymentProcessing': 'Procesamiento de Pago',
        'paymentDesc': 'Actualmente aceptamos USDT TRC-20 y Telegram para miembros.',
        'networkUsdt': 'Red USDT TRC-20',
        'copyAddress': 'Copiar Dirección',
        'addressCopied': '¡Copiado!',
        'telegramSupport': 'Soporte de Telegram',
        'telegramSupportDesc': 'Contacta a nuestros agentes por Telegram.',
        'uploadReceipt': 'Subir Recibo de Pago',
        'submitReceipt': 'Enviar Recibo',
        'processingReceipt': 'Procesando...',
        'verificationPending': 'Verificación Pendiente',
        'verificationDesc': 'Tu recibo está siendo revisado. El acceso será en 2-4 horas.',
        'accountDashboard': 'Panel de Cuenta',
        'terminalAccess': 'Acceso a Terminal Phase-X',
        'managePlan': 'Gestionar Plan',
        'aiAnalytics': 'Analíticas de IA',
        'tokensLabel': 'Tokens',
        'liveProcessingActive': 'Procesamiento en Vivo Activo',
        'integrationInactive': 'Integración Inactiva',
        'topUpTokens': 'Recargar Tokens',
        'unlockAiAddon': 'Desbloquear IA',
        'billingCycle': 'Ciclo de Facturación',
        'nextPaymentDue': 'Próximo pago en 14 días.',
        'aiMarketInsight': 'VISIÓN DE MERCADO IA',
        'userProfile': 'Perfil de Usuario'
    },
    'ru': {
        'selectYourPlan': 'Выберите свой план',
        'unlockFullClarity': 'Откройте полную ясность рынка',
        'selectPlatformPackage': 'Выберите пакет платформы',
        'planMonthly': 'Месячный план',
        'planQuarterly': 'Квартальный план',
        'planSemiAnnual': 'Полугодовой план',
        'planAnnual': 'Годовой план',
        'billedEvery3Months': 'Оплата каждые 3 месяца',
        'billedEvery6Months': 'Оплата каждые 6 месяцев',
        'billedEveryYear': 'Оплата каждый год',
        'save10': 'Экономия 10%',
        'save15': 'Экономия 15%',
        'save20': 'Экономия 20%',
        'aiMarketAddon': 'Модуль ИИ для рынка',
        'phaseXCoreRadar': 'Радар ИИ Phase X Core',
        'aiAddonDesc': 'Получите живой контекст и сигналы исполнения с помощью нейронной сети Phase-X.',
        'perMonthSub': '+$20/мес',
        'aiTokensIncluded': '3,000 ИИ токенов',
        'tokensRollOver': 'Токены переносятся при активной подписке.',
        'paymentProcessing': 'Обработка платежей',
        'paymentDesc': 'В настоящее время мы принимаем USDT TRC-20 и Telegram.',
        'networkUsdt': 'Сеть USDT TRC-20',
        'copyAddress': 'Копировать адрес',
        'addressCopied': 'Скопировано!',
        'telegramSupport': 'Поддержка Telegram',
        'telegramSupportDesc': 'Свяжитесь с нашими агентами через Telegram.',
        'uploadReceipt': 'Загрузить квитанцию об оплате',
        'submitReceipt': 'Отправить квитанцию',
        'processingReceipt': 'Обработка...',
        'verificationPending': 'Ожидание проверки',
        'verificationDesc': 'Ваша квитанция проверяется. Доступ будет предоставлен в течение 2-4 часов.',
        'accountDashboard': 'Панель аккаунта',
        'terminalAccess': 'Доступ к терминалу Phase-X',
        'managePlan': 'Управление планом',
        'aiAnalytics': 'Аналитика ИИ',
        'tokensLabel': 'Токены',
        'liveProcessingActive': 'Живая обработка активна',
        'integrationInactive': 'Интеграция неактивна',
        'topUpTokens': 'Пополнить токены',
        'unlockAiAddon': 'Разблокировать модуль ИИ',
        'billingCycle': 'Цикл оплаты',
        'nextPaymentDue': 'Следующий платеж через 14 дней.',
        'aiMarketInsight': 'ОБЗОР РЫНКА ОТ ИИ',
        'userProfile': 'Профиль Пользователя'
    },
    'tr': {
        'selectYourPlan': 'Planınızı Seçin',
        'unlockFullClarity': 'Tam Piyasa Netliğini Açın',
        'selectPlatformPackage': 'Platform Paketini Seçin',
        'planMonthly': 'Aylık Plan',
        'planQuarterly': '3 Aylık Plan',
        'planSemiAnnual': '6 Aylık Plan',
        'planAnnual': 'Yıllık Plan',
        'billedEvery3Months': 'Her 3 Ayda Bir Faturalandırılır',
        'billedEvery6Months': 'Her 6 Ayda Bir Faturalandırılır',
        'billedEveryYear': 'Her Yıl Faturalandırılır',
        'save10': '%10 Tasarruf',
        'save15': '%15 Tasarruf',
        'save20': '%20 Tasarruf',
        'aiMarketAddon': 'Yapay Zeka Piyasa Eklentisi',
        'phaseXCoreRadar': 'Phase X Core YZ Radarı',
        'aiAddonDesc': 'Phase-X Sinir Ağı ile canlı bağlam ve gelişmiş sinyaller elde edin.',
        'perMonthSub': '+$20/ay',
        'aiTokensIncluded': '3.000 YZ Jetonu',
        'tokensRollOver': 'Abonelik aktifken jetonlar devreder.',
        'paymentProcessing': 'Ödeme İşlemi',
        'paymentDesc': 'Şu anda üyeler için USDT TRC-20 ve Telegram kabul ediyoruz.',
        'networkUsdt': 'USDT TRC-20 Ağı',
        'copyAddress': 'Adresi Kopyala',
        'addressCopied': 'Kopyalandı!',
        'telegramSupport': 'Telegram Desteği',
        'telegramSupportDesc': 'Sıraya girmeden ajanlarımızla Telegram üzerinden iletişime geçin.',
        'uploadReceipt': 'Ödeme Makbuzu Yükle',
        'submitReceipt': 'Makbuzu Gönder',
        'processingReceipt': 'İşleniyor...',
        'verificationPending': 'Doğrulama Bekleniyor',
        'verificationDesc': 'Makbuzunuz inceleniyor. Erişim 2-4 saat içinde sağlanacaktır.',
        'accountDashboard': 'Hesap Paneli',
        'terminalAccess': 'Phase-X Terminal Erişimi',
        'managePlan': 'Planı Yönet',
        'aiAnalytics': 'YZ Analitiği',
        'tokensLabel': 'Jetonlar',
        'liveProcessingActive': 'Canlı İşlem Aktif',
        'integrationInactive': 'Entegrasyon Pasif',
        'topUpTokens': 'Jeton Yükle',
        'unlockAiAddon': 'YZ Eklentisini Aç',
        'billingCycle': 'Fatura Döngüsü',
        'nextPaymentDue': 'Sonraki ödeme 14 gün içinde.',
        'aiMarketInsight': 'YZ PIYASA GÖRÜSÜ',
        'userProfile': 'Kullanıcı Profili'
    }
}

files = ['en.ts', 'ar.ts', 'fr.ts', 'es.ts', 'ru.ts', 'tr.ts']
base_path = 'src/app/locales/'

for filename in files:
    lang = filename.split('.')[0]
    filepath = base_path + filename
    
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
        
    # Find the closing brace `};` or `}` at the end of the file.
    # We will just insert before the last `}`
    
    # generate json string for the keys
    dict_content = translations[lang]
    # build ts syntax
    fields = []
    for k, v in dict_content.items():
        if f'"{k}":' not in content and f"'{k}':" not in content and f"{k}:" not in content:
            fields.append(f'    {k}: "{v}",')
    
    if len(fields) > 0:
        fields_str = "\n".join(fields)
        # replace last }
        last_brace = content.rfind('}')
        new_content = content[:last_brace] + "    // Subscription & Profile\n" + fields_str + "\n" + content[last_brace:]
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"Updated {filename} with {len(fields)} fields.")
    else:
        print(f"No new fields for {filename}.")
