import React from "react";
import { Target, Cpu, Activity as Pulse, Shield, Flame, Activity, Layers } from "lucide-react";
import type { MarketCategory, AnalysisTab, TrendLabel } from "./types";

export const analysisTabs: AnalysisTab[] = ["Vector Core", "Delta Engine", "Pulse Matrix", "Boundary Shell", "Power Field", "Phase X Layer", "Decision Engine"];

export const analysisTabsAr: Record<string, string> = {
    "Vector Core": "المتجهات الأساسية",
    "Delta Engine": "محرك التغيرات",
    "Pulse Matrix": "مصفوفة النبض",
    "Boundary Shell": "الغلاف الحدودي",
    "Power Field": "حقل القوة",
    "Phase X Layer": "طبقة المرحلة X",
    "Decision Engine": "محرك اتخاذ القرار",
};

export const analysisTabIcons: Record<string, React.ReactNode> = {
    "Vector Core": <Target className="w-4 h-4" />,
    "Delta Engine": <Cpu className="w-4 h-4" />,
    "Pulse Matrix": <Pulse className="w-4 h-4" />,
    "Boundary Shell": <Shield className="w-4 h-4" />,
    "Power Field": <Flame className="w-4 h-4" />,
    "Phase X Layer": <Layers className="w-4 h-4" />,
    "Decision Engine": <Activity className="w-4 h-4" />,
};

export const tfColumns = ["5M", "10M", "15M", "20M", "30M", "H1", "H2", "H3", "H4", "H6", "H8", "Daily"];

export const vcTfColumns = ["M5", "M10", "M15", "M20", "M30", "H1", "H2", "H3", "H4", "H6", "H8", "D1"];
export const vcTfLabels = ["5M", "10M", "15M", "20M", "30M", "H1", "H2", "H3", "H4", "H6", "H8", "D1"];

export const symbolToJsonKey: Record<string, string> = {
    "ADAUSD": "ADAUSD.lv - CRYPTO",
    "ATMUSD": "ATMUSD.lv - CRYPTO",
    "AVAUSD": "AVAUSD.lv - CRYPTO",
    "AXSUSD": "AXSUSD.lv - CRYPTO",
    "BCHUSD": "BCHUSD.lv - CRYPTO",
    "BNBUSD": "BNBUSD.lv - CRYPTO",
    "BTCUSD": "BTCUSD.lv - CRYPTO",
    "COMUSD": "COMUSD.lv - CRYPTO",
    "DOTUSD": "DOTUSD.lv - CRYPTO",
    "DSHUSD": "DSHUSD.lv - CRYPTO",
    "ETCUSD": "ETCUSD.lv - CRYPTO",
    "ETHUSD": "ETHUSD.lv - CRYPTO",
    "LNKUSD": "LNKUSD.lv - CRYPTO",
    "LTCUSD": "LTCUSD.lv - CRYPTO",
    "SOLUSD": "SOLUSD.lv - CRYPTO",
    "TRUUSD": "TRUUSD.lv - CRYPTO",
    "UNIUSD": "UNIUSD.lv - CRYPTO",
    "XRPUSD": "XRPUSD.lv - CRYPTO",
    "YFIUSD": "YFIUSD.lv - CRYPTO",
    "AUDCAD": "AUDCAD.sd - FOREX",
    "AUDCHF": "AUDCHF.sd - FOREX",
    "AUDJPY": "AUDJPY.sd - FOREX",
    "AUDNZD": "AUDNZD.sd - FOREX",
    "AUDUSD": "AUDUSD.sd - FOREX",
    "CADCHF": "CADCHF.sd - FOREX",
    "CADJPY": "CADJPY.sd - FOREX",
    "CHFJPY": "CHFJPY.sd - FOREX",
    "EURAUD": "EURAUD.sd - FOREX",
    "EURCAD": "EURCAD.sd - FOREX",
    "EURCHF": "EURCHF.sd - FOREX",
    "EURGBP": "EURGBP.sd - FOREX",
    "EURJPY": "EURJPY.sd - FOREX",
    "EURNZD": "EURNZD.sd - FOREX",
    "EURUSD": "EURUSD.sd - FOREX",
    "GBPAUD": "GBPAUD.sd - FOREX",
    "GBPCAD": "GBPCAD.sd - FOREX",
    "GBPCHF": "GBPCHF.sd - FOREX",
    "GBPJPY": "GBPJPY.sd - FOREX",
    "GBPNZD": "GBPNZD.sd - FOREX",
    "GBPUSD": "GBPUSD.sd - FOREX",
    "NZDCAD": "NZDCAD.sd - FOREX",
    "NZDCHF": "NZDCHF.sd - FOREX",
    "NZDJPY": "NZDJPY.sd - FOREX",
    "NZDUSD": "NZDUSD.sd - FOREX",
    "USDCAD": "USDCAD.sd - FOREX",
    "USDCHF": "USDCHF.sd - FOREX",
    "USDJPY": "USDJPY.sd - FOREX",
    "XAUUSD": "XAUUSD.sd - COMMODITY",
    "XAGUSD": "XAGUSD.sd - COMMODITY",
    "UKOILRoll": "UKOILRoll - COMMODITY",
    "USOILRoll": "USOILRoll - COMMODITY",
    "DE40Roll": "DE40Roll - INDEX",
    "JP225Roll": "JP225Roll - INDEX",
    "UK100Roll": "UK100Roll - INDEX",
    "UT100Roll": "UT100Roll - INDEX",
    "US30Roll": "US30Roll - INDEX",
    "US500Roll": "US500Roll - INDEX",
    "VIXRoll": "VIXRoll - INDEX",
    "NL25Roll": "NL25Roll - INDEX",
    "NORWAY25Roll": "NORWAY25Roll - INDEX",
    "RUSS2000": "RUSS2000 - INDEX",
    "EU50Roll": "EU50Roll - INDEX",
    "FRA40Roll": "FRA40Roll - INDEX",
    "AUS200Roll": "AUS200Roll - INDEX",
    "CHshares": "CHshares - INDEX",
    "SWISS20Roll": "SWISS20Roll - INDEX",
    "CHINA50Roll": "CHINA50Roll - INDEX",
    "ESP35Roll": "ESP35Roll - INDEX",
    "HK50Roll": "HK50Roll - INDEX",
    "AMD": "AMD - OTHER",
    "AIG": "AIG - OTHER",
};

export const defaultAnalysisSources: Record<AnalysisTab, any[]> = {
    "Vector Core": [],
    "Delta Engine": [],
    "Pulse Matrix": [],
    "Boundary Shell": [],
    "Power Field": [],
    "Phase X Layer": [],
    "Decision Engine": []
};

export const trendAr: Record<string, string> = {
    "Bullish": "صعودي", "Bearish": "هبوطي", "Neutral": "محايد",
    "Strong": "قوي", "Moderate": "معتدل", "Weak": "ضعيف",
    "Upward": "صاعد", "Downward": "هابط",
    "Expansion": "توسع", "Contraction": "انكماش", "Transition": "تحول",
    "Low": "منخفض", "High": "مرتفع",
    "Directional": "اتجاهي", "Ranging": "عرضي", "Transitional": "انتقالي",
    "Normal": "طبيعي", "Expanding": "متوسع",
    "Strong Uptrend": "صعود قوي", "Strong Downtrend": "هبوط قوي",
    "Strong Upt": "صعود قوي", "Strong Dow": "هبوط قوي",
    "Strong Downward": "هبوط قوي", "Buy": "شراء", "Sell": "بيع",
    "Short-Term": "قصير المدى", "Medium-Term": "متوسط المدى", "Long-Term": "طويل المدى",
    "STRONG BULLISH EXPANSION": "توسع صعودي قوي", "MODERATE BULLISH": "صعودي معتدل",
    "WEAK BEARISH": "هبوطي ضعيف", "MODERATE DOWNTREND": "هبوط معتدل",
    "Bullish Expansion": "توسع صعودي", "Bearish Expansion": "توسع هبوطي",
    "Compression": "انضغاط", "Range": "عرضي", "Developing": "قيد التطور", "Elevated": "مرتفع",
};

export const trendRu: Record<string, string> = {
    "Bullish": "Бычий", "Bearish": "Медвежий", "Neutral": "Нейтральный",
    "Strong": "Сильный", "Moderate": "Умеренный", "Weak": "Слабый",
    "Upward": "Восходящий", "Downward": "Нисходящий",
    "Expansion": "Расширение", "Contraction": "Сжатие", "Transition": "Переход",
    "Low": "Низкий", "High": "Высокий",
    "Directional": "направленный", "Ranging": "в диапазоне", "Transitional": "переходный",
    "Normal": "Нормальный", "Expanding": "Расширяющийся",
    "Strong Uptrend": "Сильный восходящий тренд", "Strong Downtrend": "Сильный нисходящий тренд",
    "Strong Upt": "Сильный восходящий", "Strong Dow": "Сильный нисходящий",
    "Strong Downward": "Сильный нисходящий", "Buy": "Купить", "Sell": "Продать",
    "Short-Term": "Краткосрочный", "Medium-Term": "Среднесрочный", "Long-Term": "Долгосрочный",
    "STRONG BULLISH EXPANSION": "СИЛЬНОЕ БЫЧЬЕ РАСШИРЕНИЕ", "MODERATE BULLISH": "УМЕРЕННЫЙ БЫЧИЙ ТРЕНД",
    "WEAK BEARISH": "СЛАБЫЙ МЕДВЕЖИЙ", "MODERATE DOWNTREND": "УМЕРЕННЫЙ НИСХОДЯЩИЙ ТРЕНД",
    "Bullish Expansion": "Бычье расширение", "Bearish Expansion": "Медвежье расширение",
    "Compression": "Сжатие", "Range": "Диапазон", "Developing": "Развивающийся", "Elevated": "Повышенный",
};

export const trendTr: Record<string, string> = {
    "Bullish": "Yükseliş", "Bearish": "Düşüş", "Neutral": "Nötr",
    "Strong": "Güçlü", "Moderate": "Ilımlı", "Weak": "Zayıf",
    "Upward": "Yukarı", "Downward": "Aşağı",
    "Expansion": "Genişleme", "Contraction": "Daralma", "Transition": "Geçiş",
    "Low": "Düşük", "High": "Yüksek",
    "Directional": "Yönlü", "Ranging": "Menzil İçinde", "Transitional": "Geçiş Dönemi",
    "Normal": "Normal", "Expanding": "Genişleyen",
    "Strong Uptrend": "Güçlü Yükseliş Trendi", "Strong Downtrend": "Güçlü Düşüş Trendi",
    "Strong Upt": "Güçlü Yükseliş", "Strong Dow": "Güçlü Düşüş",
    "Strong Downward": "Güçlü Düşüş", "Buy": "Al", "Sell": "Sat",
    "Short-Term": "Kısa Vadeli", "Medium-Term": "Orta Vadeli", "Long-Term": "Uzun Vadeli",
    "STRONG BULLISH EXPANSION": "GÜÇLÜ YÜKSELİŞ GENİŞLEMESİ", "MODERATE BULLISH": "ILIMLI YÜKSELİŞ",
    "WEAK BEARISH": "ZAYIF DÜŞÜŞ", "MODERATE DOWNTREND": "ILIMLI DÜŞÜŞ TRENDİ",
    "Bullish Expansion": "Yükseliş Genişlemesi", "Bearish Expansion": "Düşüş Genişlemesi",
    "Compression": "Sıkışma", "Range": "Aralık", "Developing": "Gelişiyor", "Elevated": "Yükselmiş",
};

export const trendFr: Record<string, string> = {
    "Bullish": "Haussier", "Bearish": "Baissier", "Neutral": "Neutre",
    "Strong": "Fort", "Moderate": "Modéré", "Weak": "Faible",
    "Upward": "Hausse", "Downward": "Baisse",
    "Expansion": "Expansion", "Contraction": "Contraction", "Transition": "Transition",
    "Low": "Bas", "High": "Haut",
    "Directional": "Directionnel", "Ranging": "En Rang", "Transitional": "En Transition",
    "Normal": "Normal", "Expanding": "En Expansion",
    "Strong Uptrend": "Tendance Haussière Forte", "Strong Downtrend": "Tendance Baissière Forte",
    "Strong Upt": "Hausse Forte", "Strong Dow": "Baisse Forte",
    "Strong Downward": "Forte Baisse", "Buy": "Acheter", "Sell": "Vendre",
    "Short-Term": "Court Terme", "Medium-Term": "Moyen Terme", "Long-Term": "Long Terme",
    "STRONG BULLISH EXPANSION": "FORTE EXPANSION HAUSSIÈRE", "MODERATE BULLISH": "HAUSSIER MODÉRÉ",
    "WEAK BEARISH": "BAISSIER FAIBLE", "MODERATE DOWNTREND": "TENDANCE BAISSIÈRE MODÉRÉE",
    "Bullish Expansion": "Expansion Haussière", "Bearish Expansion": "Expansion Baissière",
    "Compression": "Compression", "Range": "Rang", "Developing": "En Développement", "Elevated": "Élevé",
};

export const trendEs: Record<string, string> = {
    "Bullish": "Alcista", "Bearish": "Bajista", "Neutral": "Neutral",
    "Strong": "Fuerte", "Moderate": "Moderado", "Weak": "Débil",
    "Upward": "Alza", "Downward": "Baja",
    "Expansion": "Expansión", "Contraction": "Contracción", "Transition": "Transición",
    "Low": "Bajo", "High": "Alto",
    "Directional": "Direccional", "Ranging": "En Rango", "Transitional": "En Transición",
    "Normal": "Normal", "Expanding": "En Expansión",
    "Strong Uptrend": "Tensión Alcista Fuerte", "Strong Downtrend": "Tensión Bajista Fuerte",
    "Strong Upt": "Alza Fuerte", "Strong Dow": "Baja Fuerte",
    "Strong Downward": "Baja Fuerte", "Buy": "Comprar", "Sell": "Vender",
    "Short-Term": "Corto Plazo", "Medium-Term": "Medio Plazo", "Long-Term": "Largo Plazo",
    "STRONG BULLISH EXPANSION": "FUERTE EXPANSIÓN ALCISTA", "MODERATE BULLISH": "ALCISTA MODERADO",
    "WEAK BEARISH": "BAJISTA DÉBIL", "MODERATE DOWNTREND": "TENDENCIA BAJISTA MODERADA",
    "Bullish Expansion": "Expansión Alcista", "Bearish Expansion": "Expansión Bajista",
    "Compression": "Compresión", "Range": "Rango", "Developing": "En Desarrollo", "Elevated": "Elevado",
};

export const i18n: Record<string, Record<string, string>> = {
    ar: {
        title: "نظام الديناميكيات الهيكلية", score: "النتيجة", confidence: "الثقة",
        timeframe: "الإطار الزمني", layer: "الطبقة", globalState: "حالة السوق العالمية",
        phase: "المرحلة", volatility: "التذبذب", risk: "المخاطرة",
        trend: "الاتجاه", momentum: "الزخم", bias: "الانحياز", reversal: "الانعكاس",
        marketFilter: "تصفية الأسواق", globalScore: "النتيجة الكلية",
        layerSummary: "ملخص الطبقات", dynamicsOutput: "مخرجات الديناميكيات",
        primaryTrend: "الاتجاه الرئيسي", momentumState: "حالة الزخم",
        structuralBias: "الانحياز الهيكلي", marketPhase: "مرحلة السوق",
        reversalRisk: "مخاطر الانعكاس", strength: "القوة", alignment: "التوافق",
        total: "المجموع", classification: "التصنيف",
        shortTerm: "قصير المدى", mediumTerm: "متوسط المدى", longTerm: "طويل المدى",
        vectorCore: "المتجهات الأساسية", deltaEngine: "محرك التغيرات", pulseMatrix: "مصفوفة النبض", boundaryShell: "الغلاف الحدودي", powerField: "حقل القوة", phaseXLayer: "طبقة المرحلة X", decisionEngine: "محرك اتخاذ القرار",
        all: "الكل", forex: "فوركس", commodities: "سلع", indices: "مؤشرات", crypto: "عملات رقمية", other: "أخرى",
        aiTitle: "تحليل الذكاء الاصطناعي", aiTextPart1: "تشير البيانات الحالية إلى اتجاه", aiTextPart2: "مدعوماً بـ زخم", aiTextPart3: "و انحياز", aiTextPart4: "يتشكل هذا السلوك ضمن مرحلة", aiTextPart5: "مع دخول السوق في حالة المرحلة السوقية", aiTextPart6: "يظهر مستوى تذبذب", aiTextPart7: "بينما يتم تقييم مخاطر الانعكاس على أنها", aiTextPart8: "وتعكس درجة ثقة", aiHigh: "عالية", aiMed: "متوسطة", aiLow: "منخفضة", aiTextPart9: "وضوح الإشارة الكمية وتوافق العوامل الداعمة للحالة السوقية.",
    },
    en: {
        title: "Structural Dynamics", score: "Score", confidence: "Confidence",
        timeframe: "Timeframe", layer: "Layer", globalState: "GLOBAL MARKET STATE",
        phase: "Phase", volatility: "Volatility", risk: "Risk",
        trend: "Trend", momentum: "Momentum", bias: "Bias", reversal: "Reversal",
        marketFilter: "MARKET FILTER", globalScore: "GLOBAL SCORE",
        layerSummary: "LAYER SUMMARY", dynamicsOutput: "DYNAMICS OUTPUT",
        primaryTrend: "Primary Trend", momentumState: "Momentum State",
        structuralBias: "Structural Bias", marketPhase: "Market Phase",
        reversalRisk: "Reversal Risk", strength: "Strength", alignment: "Alignment",
        total: "Total", classification: "Classification",
        shortTerm: "Short-Term", mediumTerm: "Medium-Term", longTerm: "Long-Term",
        vectorCore: "Vector Core", deltaEngine: "Delta Engine", pulseMatrix: "Pulse Matrix", boundaryShell: "Boundary Shell", powerField: "Power Field", phaseXLayer: "Phase X Layer", decisionEngine: "Decision Engine",
        all: "All", forex: "Forex", commodities: "Commodities", indices: "Indices", crypto: "Crypto", other: "Other",
        aiTitle: "AI MARKET INSIGHT", aiTextPart1: "The current market state reflects a Primary Trend", aiTextPart2: "supported by Momentum", aiTextPart3: "and a Structural Bias", aiTextPart4: "This behavior appears within a Phase", aiTextPart5: "while the Market Phase is characterized by", aiTextPart6: "Volatility conditions remain", aiTextPart7: "and Reversal Risk is assessed as", aiTextPart8: "The Confidence", aiHigh: "High Confidence", aiMed: "Medium Confidence", aiLow: "Low Confidence", aiTextPart9: "level reflects strong alignment between the underlying quantitative factors.",
    },
    ru: {
        title: "Структурная Динамика", score: "Счет", confidence: "Уверенность",
        timeframe: "Таймфрейм", layer: "Слой", globalState: "ГЛОБАЛЬНОЕ СОСТОЯНИЕ РЫНКА",
        phase: "Фаза", volatility: "Волатильность", risk: "Риск",
        trend: "Тренд", momentum: "Импульс", bias: "Смещение", reversal: "Разворот",
        marketFilter: "ФИЛЬТР РЫНКА", globalScore: "ГЛОБАЛЬНЫЙ СЧЕТ",
        layerSummary: "СВОДКА СЛОЯ", dynamicsOutput: "ВЫВОД ДИНАМИКИ",
        primaryTrend: "Основной тренд", momentumState: "Состояние импульса",
        structuralBias: "Структурное смещение", marketPhase: "Фаза рынка",
        reversalRisk: "Риск разворота", strength: "Сила", alignment: "Согласование",
        total: "Итого", classification: "Классификация",
        shortTerm: "Краткосрочный", mediumTerm: "Среднесрочный", longTerm: "Долгосрочный",
        vectorCore: "Векторное Ядро", deltaEngine: "Дельта-Движок", pulseMatrix: "Импульсная Матрица", boundaryShell: "Граничная Оболочка", powerField: "Силовое Поле", phaseXLayer: "Слой Phase X", decisionEngine: "Движок Решений",
        all: "Все", forex: "Форекс", commodities: "Сырье", indices: "Индексы", crypto: "Криптовалюты", other: "Другое",
        aiTitle: "АНАЛИЗ ИИ", aiTextPart1: "Текущее состояние рынка отражает основной тренд", aiTextPart2: "поддерживаемый импульсом", aiTextPart3: "и структурным смещением", aiTextPart4: "Это поведение проявляется в фазе", aiTextPart5: "в то время как фаза рынка характеризуется как", aiTextPart6: "Условия волатильности остаются", aiTextPart7: "а риск разворота оценивается как", aiTextPart8: "Степень уверенности", aiHigh: "Высокая Уверенность", aiMed: "Средняя Уверенность", aiLow: "Низкая Уверенность", aiTextPart9: "отражает сильное согласование базовых количественных факторов.",
    },
    tr: {
        title: "Yapısal Dinamikler", score: "Skor", confidence: "Güven",
        timeframe: "Zaman Dilimi", layer: "Katman", globalState: "KÜRESEL PİYASA DURUMU",
        phase: "Aşama", volatility: "Volatilite", risk: "Risk",
        trend: "Eğilim", momentum: "İvme", bias: "Eğilim", reversal: "Tersine Dönüş",
        marketFilter: "PİYASA FİLTRESİ", globalScore: "KÜRESEL SKOR",
        layerSummary: "KATMAN ÖZETİ", dynamicsOutput: "DİNAMİKLER ÇIKTISI",
        primaryTrend: "Ana Eğilim", momentumState: "İvme Durumu",
        structuralBias: "Yapısal Eğilim", marketPhase: "Piyasa Aşaması",
        reversalRisk: "Tersine Dönüş Riski", strength: "Güç", alignment: "Uyum",
        total: "Toplam", classification: "Sınıflandırma",
        shortTerm: "Kısa Vadeli", mediumTerm: "Orta Vadeli", longTerm: "Uzun Vadeli",
        vectorCore: "Vektör Çekirdeği", deltaEngine: "Delta Motoru", pulseMatrix: "Puls Matrisi", boundaryShell: "Sınır Kabuğu", powerField: "Güç Alanı", phaseXLayer: "Phase X Katmanı", decisionEngine: "Karar Motoru",
        all: "Tümü", forex: "Forex", commodities: "Emtia", indices: "Endeksler", crypto: "Kripto", other: "Diğer",
        aiTitle: "YAPAY ZEKA ANALİZİ", aiTextPart1: "Mevcut piyasa durumu ana eğilimi yansıtır:", aiTextPart2: "şu ivme ile destekleniyor:", aiTextPart3: "ve yapısal eğilim", aiTextPart4: "Bu davranış şu aşamada ortaya çıkar:", aiTextPart5: "piyasa aşaması şununla karakterize edilir:", aiTextPart6: "Volatilite koşulları kalır", aiTextPart7: "ve Tersine Dönüş Riski şu şekilde değerlendirilir:", aiTextPart8: "Güven derecesi", aiHigh: "Yüksek Güven", aiMed: "Orta Güven", aiLow: "Düşük Güven", aiTextPart9: "temel nicel faktörler arasındaki güçlü uyumu yansıtır.",
    },
    fr: {
        title: "Dynamiques Structurelles", score: "Score", confidence: "Confiance",
        timeframe: "Délai", layer: "Couche", globalState: "ÉTAT GLOBAL DU MARCHÉ",
        phase: "Phase", volatility: "Volatilité", risk: "Risque",
        trend: "Tendance", momentum: "Dynamique", bias: "Biais", reversal: "Renversement",
        marketFilter: "FILTRE DU MARCHÉ", globalScore: "SCORE GLOBAL",
        layerSummary: "RÉSUMÉ DES COUCHES", dynamicsOutput: "RÉSULTAT DES DYNAMIQUES",
        primaryTrend: "Tendance Principale", momentumState: "État de la Dynamique",
        structuralBias: "Biais Structurel", marketPhase: "Phase du Marché",
        reversalRisk: "Risque de Renversement", strength: "Force", alignment: "Alignement",
        total: "Total", classification: "Classification",
        shortTerm: "Court Terme", mediumTerm: "Moyen Terme", longTerm: "Long Terme",
        vectorCore: "Noyau Vectoriel", deltaEngine: "Moteur Delta", pulseMatrix: "Matrice d'Impulsion", boundaryShell: "Coquille de Limite", powerField: "Champ de Force", phaseXLayer: "Couche Phase X", decisionEngine: "Moteur de Décision",
        all: "Tout", forex: "Forex", commodities: "Matières Premières", indices: "Indices", crypto: "Crypto", other: "Autre",
        aiTitle: "ANALYSE DE L'IA", aiTextPart1: "L'état actuel du marché reflète une tendance principale", aiTextPart2: "soutenue par une dynamique", aiTextPart3: "et un biais structurel", aiTextPart4: "Ce comportement apparaît dans une phase", aiTextPart5: "tandis que la phase du marché est caractérisée par", aiTextPart6: "Les conditions de volatilité", aiTextPart7: "et le risque de renversement est évalué comme", aiTextPart8: "Le niveau de confiance", aiHigh: "Confiance Haute", aiMed: "Confiance Moyenne", aiLow: "Confiance Basse", aiTextPart9: "reflète un alignement fort entre les facteurs quantitatifs sous-jacents.",
    },
    es: {
        title: "Dinámicas Estructurales", score: "Puntaje", confidence: "Confianza",
        timeframe: "Intervalo", layer: "Capa", globalState: "ESTADO GLOBAL DEL MERCADO",
        phase: "Fase", volatility: "Volatilidad", risk: "Riesgo",
        trend: "Tendencia", momentum: "Impulso", bias: "Sesgo", reversal: "Reversión",
        marketFilter: "FILTRO DE MERCADO", globalScore: "PUNTAJE GLOBAL",
        layerSummary: "RESUMEN DE CAPA", dynamicsOutput: "SALIDA DE DINÁMICAS",
        primaryTrend: "Tendencia Primaria", momentumState: "Estado de Impulso",
        structuralBias: "Sesgo Estructural", marketPhase: "Fase del Mercado",
        reversalRisk: "Riesgo de Reversión", strength: "Fuerza", alignment: "Alineación",
        total: "Total", classification: "Clasificación",
        shortTerm: "Corto Plazo", mediumTerm: "Medio Plazo", longTerm: "Largo Plazo",
        vectorCore: "Núcleo Vectorial", deltaEngine: "Motor Delta", pulseMatrix: "Matriz de Pulso", boundaryShell: "Caparazón Limítrofe", powerField: "Campo de Fuerza", phaseXLayer: "Capa Phase X", decisionEngine: "Motor de Decisión",
        all: "Todo", forex: "Forex", commodities: "Materias Primas", indices: "Índices", crypto: "Cripto", other: "Otro",
        aiTitle: "ANÁLISIS DE LA IA", aiTextPart1: "El estado actual del mercado refleja una tendencia primaria", aiTextPart2: "apoyado por un impulso", aiTextPart3: "y un sesgo estructural", aiTextPart4: "Este comportamiento aparece dentro de una fase", aiTextPart5: "mientras la fase del mercado se caracteriza por", aiTextPart6: "Las condiciones de volatilidad", aiTextPart7: "y el riesgo de reversión se evalúa como", aiTextPart8: "El nivel de confianza", aiHigh: "Alta Confianza", aiMed: "Confianza Media", aiLow: "Baja Confianza", aiTextPart9: "refleja una fuerte alineación entre los factores cuantitativos subyacentes.",
    },
};
