export const INITIAL_PROVIDERS: Record<string, "loading" | "ok" | "error" | "empty"> = {
  ForexFactory: "loading",
  "Crypto News": "loading",
  "Global Market News": "loading",
  "Business News": "loading",
  CoinDesk: "loading",
  "Market Feed": "loading",
  "Yahoo Finance": "loading",
  "Financial Times": "loading",
  "Seeking Alpha": "loading",
  MarketWatch: "loading",
  "The Block": "loading",
  Decrypt: "loading",
  FXStreet: "loading",
  ForexLive: "loading",
  CNBC: "loading",
  "Investing.com": "loading",
  "Wall Street Journal": "loading",
  Forbes: "loading",
  DailyFX: "loading",
  "Investing.com Forex": "loading",
  "Finance Magnates": "loading",
  Cointelegraph: "loading",
};
