export const brokers = [
  {
    name: "IC Markets",
    discount: "25%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#fff",
    text: "#0a1628",
  },
  {
    name: "PrimeXBT",
    discount: "50%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#1a2332",
    text: "#fff",
  },
  {
    name: "OctaFX",
    discount: "50%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#00a651",
    text: "#fff",
  },
  {
    name: "eToro",
    discount: "20%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#6bbd46",
    text: "#fff",
  },
  {
    name: "Vantage FX",
    discount: "30%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#e8380d",
    text: "#fff",
  },
  {
    name: "Windsor Brokers",
    discount: "25%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#1a3a5c",
    text: "#fff",
  },
  {
    name: "Exness",
    discount: "40%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#facc15",
    text: "#000",
  },
  {
    name: "LiteForex",
    discount: "30%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#003d7a",
    text: "#fff",
  },
  {
    name: "IUX",
    discount: "35%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#1c1c2e",
    text: "#fff",
  },
  {
    name: "Swissquote",
    discount: "20%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#e4002b",
    text: "#fff",
  },
  {
    name: "FxPro",
    discount: "30%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#ff5722",
    text: "#fff",
  },
  {
    name: "iFOREX",
    discount: "25%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#0054a6",
    text: "#fff",
  },
  {
    name: "FP Markets",
    discount: "35%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#00295b",
    text: "#fff",
  },
  {
    name: "RoboForex",
    discount: "30%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#2196f3",
    text: "#fff",
  },
  {
    name: "XM",
    discount: "50%",
    url: "https://t.me/PhaseX_Ai",
    bg: "#c4161c",
    text: "#fff",
  },
];
